# Prison Module Configuration
# Version: 1.0.0

# Mine settings
mines:
  reset-interval: 300 # 5 minutes
  broadcast-reset: true
  teleport-on-reset: true
  teleport-location: "spawn" # spawn or entrance

# Rank settings
ranks:
  #SQL TABLE
  table: "PlayerMinesRank"
  use-vault-integration: true
  default-rank: "A"
  # Rank progression (A-Z) = mine progression

# Prestige settings
prestige:
  personal-mine-unlock-level: 5
  cost-multiplier: 1.5 # Each prestige costs 1.5x more than the previous
  base-cost: 1000000
  max-level: 100
  benefits:
    token-multiplier: 0.1 # +10% tokens per prestige level
    sell-multiplier: 0.05 # +5% sell price per prestige level
    mine-fortune: 0.02 # +2% fortune chance per prestige level

# Personal mine settings
personal-mines:
  base-size: 5 # Base size in blocks (5x5)
  max-size-level: 10
  size-upgrade-cost-base: 50000
  size-upgrade-cost-multiplier: 1.5
  
  max-reset-speed-level: 10
  reset-speed-upgrade-cost-base: 75000
  reset-speed-upgrade-cost-multiplier: 1.5
  
  max-composition-level: 10
  composition-upgrade-cost-base: 100000
  composition-upgrade-cost-multiplier: 1.5
  
# Enchant settings
enchants:
  max-level: 1000
  allow-combining: true
  #SQL
  table: "PlayerEnchantLevels"